version: '3.8'

networks:
  proxy-network-prod:
    name: proxy-network-prod
  zivelogin-network-prod:
    name: zivelogin-network-prod
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"  # Custom subnet for static IP allocation

services:
  # Backend Service
  zivelogin-backend:
    build:
      context: ./Hrumbles-Backend-main
      dockerfile: Dockerfile
    image: opt-zivelogin-backend:latest
    container_name: zivelogin-backend
    restart: unless-stopped
    networks:
      - proxy-network-prod
      - zivelogin-network-prod
    ports:
      - "5001:8080"  # Expose backend on port 5001
    environment:
      MONGO_URL: mongodb://zivedbadmin:Co1mbat0re9091@zivelogin-mongo:27017/master?authSource=admin
      PORT: 8080
      JWT_SECRET: mysecret123
      # Gmail Configuration
      SMPT_HOST: smtp.googlemail.com
      SMPT_PORT: 587
      SMPT_PASSWORD: nfyunxrmdsgxmlmp
      SMPT_MAIL: devlopsdemo@gmail.com
      # Outlook Configuration
      OUTLOOK_SMTP_HOST: smtp-mail.outlook.com
      OUTLOOK_SMTP_PORT: 587
      # Common Email Settings
      EMAIL_FROM: "No Reply <devlopsdemo@gmail.com>"
      ADMIN_EMAIL: sangeeth@technoladders.com
    depends_on:
      - zivelogin-mongo

  # MongoDB Service
  zivelogin-mongo:
    image: mongo:latest
    container_name: zivelogin-mongo-new  # Changed the container name to avoid conflict
    restart: unless-stopped
    networks:
      - zivelogin-network-prod
    ports:
      - "15518:27017"  # Expose MongoDB on port 15517
    volumes:
      - mongodb_data:/data/db
      - /root/cicdpipeline_new/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # Ensure this path is correct
    environment:
      MONGO_INITDB_ROOT_USERNAME: zivedbadmin
      MONGO_INITDB_ROOT_PASSWORD: Co1mbat0re9091
      MONGO_INITDB_DATABASE: master

  # Frontend Build Service
  zivelogin-frontend:
    build:
      context: ./Hrumble-Front-End-Final-main
      dockerfile: Dockerfile
    container_name: zivelogin-frontend
    restart: unless-stopped
    networks:
      - proxy-network-prod
      - zivelogin-network-prod
    ports:
      - "5002:80"
    volumes:
      - ./frontend/dist:/dist
    environment:
      VITE_BASE: "https://62.72.51.159:5001/"
      VITE_BASE_URL: "https://62.72.51.159:5001/api/v1"
    depends_on:
      - zivelogin-backend

  # NGINX Reverse Proxy
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: zivelogin-nginx
    networks:
      zivelogin-network-prod:
        ipv4_address: 192.168.1.200  # Static IP for NGINX container
    ports:
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port
    depends_on:
      - zivelogin-backend
      - zivelogin-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Ensure the path is correct

  # Portainer Service
  portainer_new:
    image: portainer/portainer-ce:latest
    container_name: portainer_new  # Changed container name to avoid conflict
    restart: unless-stopped
    networks:
      - proxy-network-prod
    ports:
      - "9100:9000"  # Expose Portainer web UI on port 9001 (changed port)
      - "9444:9443"  # Expose secured Portainer UI
    volumes:
      - /opt/portainer:/data:rw  # Volume to store Portainer data
      - /var/run/docker.sock:/var/run/docker.sock:rw  # Docker socket for management
    environment:
      - TZ=UTC

volumes:
  mongodb_data:
    name: zivelogin_mongodb_data
