version: '3.8'

networks:
  proxy-network-prod:
    name: proxy-network-prod
  zivelogin-network-prod:
    name: zivelogin-network-prod
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"

services:
  zivelogin-backend:
    build:
      context: ./Hrumbles-Backend-main
      dockerfile: Dockerfile
    image: opt-zivelogin-backend:latest
    container_name: zivelogin-backend-new
    restart: unless-stopped
    networks:
      - proxy-network-prod
      - zivelogin-network-prod
    ports:
      - "5001:8080"
    environment:
      MONGO_URL: mongodb://zivedbadmin:Co1mbat0re9091@zivelogin-mongo:27017/master?authSource=admin
      PORT: 8080
      JWT_SECRET: mysecret123
      SMPT_HOST: smtp.googlemail.com
      SMPT_PORT: 587
      SMPT_PASSWORD: nfyunxrmdsgxmlmp
      SMPT_MAIL: devlopsdemo@gmail.com
      OUTLOOK_SMTP_HOST: smtp-mail.outlook.com
      OUTLOOK_SMTP_PORT: 587
      EMAIL_FROM: "No Reply (Hrumbles.ai)"
      ADMIN_EMAIL: sangeeth@technoladders.com
    depends_on:
      - zivelogin-mongo
    volumes:
      - backend_uploads:/uploads

  zivelogin-mongo:
    image: mongo:latest
    container_name: zivelogin-mongo-new
    restart: unless-stopped
    networks:
      - zivelogin-network-prod
    ports:
      - "15518:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: zivedbadmin
      MONGO_INITDB_ROOT_PASSWORD: Co1mbat0re9091
      MONGO_INITDB_DATABASE: master

  zivelogin-frontend:
    build:
      context: ./Hrumble-Front-End-Final-main
      dockerfile: Dockerfile
    container_name: zivelogin-frontend-new
    restart: unless-stopped
    networks:
      - proxy-network-prod
      - zivelogin-network-prod
    ports:
      - "5002:80"
    volumes:
      - ./frontend/dist:/dist
    environment:
      VITE_BASE: "https://api.hrumbles.ai/"
      VITE_BASE_URL: "https://api.hrumbles.ai/api/v1"
    depends_on:
      - zivelogin-backend

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy
    environment:
      X_FRAME_OPTIONS: "sameorigin"
    networks:
      zivelogin-network-prod:
        ipv4_address: 192.168.1.200
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  portainer_new:
    image: portainer/portainer-ce:latest
    container_name: portainer_new
    restart: unless-stopped
    networks:
      - proxy-network-prod
    ports:
      - "9000:9000"
      - "9444:9443"
    volumes:
      - /opt/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - TZ=UTC

volumes:
  mongodb_data:
    driver: local
  backend_uploads:
    driver: local
